# Site settings for GitHub Pages
title: Hawatri
description: A personal blog and content platform
author: Hawatri
url: "https://fardi.github.io"
baseurl: "/HawatriLogs"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Hawatri"
      comments: false
      share: false

# Exclude from processing
exclude:
  - _site
  - .jekyll-cache
  - .jekyll-metadata
  - README.md

# Include in processing
include:
  - _posts
  - _layouts
  - _includes
  - assets
  - styles.css
