# Site settings for GitHub Pages
title: Hawatri
description: A personal blog and content platform
author: Hawatri
url: "https://[YOUR_USERNAME].github.io" # Change this to your GitHub Pages URL
baseurl: "/HawatriLogs" # Change this to your repository name

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Hawatri"
      comments: false
      share: false

# Exclude from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - script.js
  - pages/
  - blog/*.html
  - blog/index.json
  - _site
  - .jekyll-cache
  - .jekyll-metadata

# Include in processing
include:
  - _posts
  - _layouts
  - _includes
  - assets
  - images
